PREFIX rúian:  <https://ruian.linked.opendata.cz/slovník/>
PREFIX schema: <http://schema.org/>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?source skos:exactMatch ?target .
}
WHERE {
  ?target skos:inScheme <https://csu.opendata.cz/zdroj/řízený-slovník/47> ;
    skos:notation ?notation .
  ?source a rúian:Zsj ;
    skos:notation ?notation .
}
