PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX wd:   <http://www.wikidata.org/entity/>

CONSTRUCT {
  ?country a wd:Q6256 ;
    rdfs:label ?label .
}
WHERE {
  ?country wdt:P31 wd:Q6256 ;
    rdfs:label|skos:altLabel ?label .
  FILTER langMatches(lang(?label), "cs")
}
